#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# colors %_% so sexYXyyyXyy
alias \
				ls='ls -hN --color=auto' \
				la='ls -a' \
				grep='grep --color=auto' \
				diff='diff --color=auto' \
				ccat='highlight --out-format=ansi'
# so hard to write

alias \
				vim='nvim' \
				sudov='sudo -e ' \
				zdot='~/.config/zsh' \
				cls='clear' \
				q='exit' \
				handbrake='ghb' \
				p='sudo pacman'	\
				f='$FILE' \
				v='$EDITOR' \
				b='$BROWSER'

# Locations
alias \
				desktop="$HOME/Desktop" \
				config="$XDG_CONFIG_HOME" \
				downloads="$HOME/Downloads"

# bruh some shit happened to me don't question it
alias rm="trash"


# Other

alias \
				run-java='function lol() {javac "$1.java" && java "$1";unset -f lol}; lol' \
				fping='function boi() {ping -O "$1" | sed "s/.*no answer yet.*/Request timeout/g";unset -f boi}; boi'
