#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
exec feh --bg-scale ~/Desktop/Wallpapers/noice.jpg &
xsetroot -cursor_name left_ptr &

###### layout
setxkbmap -layout us,il -option 'grp:alt_shift_toggle'

###### mouse
xinput --set-prop 'Kingsis Corporation ZOWIE Gaming mouse' 'libinput Accel Speed' -1


###### config
bspc monitor -d web term com game other 
bspc config focused_border_color "#871e1e"
bspc config normal_border_color  "#620404"

bspc config border_width         1
bspc config window_gap          16
bspc config top_padding 	2
bspc config bottom_padding 	0
bspc config left_padding 	0
bspc config right_padding 	0

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus

###### apps
bspc rule --add Brave-browser desktop=^1 follow=on state=tiled
bspc rule --add Alacritty desktop=^2 follow=on state=tiled
bspc rule --add discord desktop=^3 follow=on state=tiled
bspc rule --add steam desktop=^4 follow=on state=tiled
bspc rule --add lunarclient desktop=^4 follow=on state=tiled
bspc rule --add corectrl desktop=^5 follow=off state=tiled

###### startup apps 
xset b off &
pgrep -x picom > /dev/null || picom &
pgrep -x lxpolkit > /dev/null || lxpolkit &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x kdeconnect-indicator > /dev/null || kdeconnect-indicator &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x corectrl > /dev/null || corectrl &

###### polybar
bash /home/audioz/.config/polybar/launch.sh &
