#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
exec feh --bg-scale ~/Desktop/Wallpapers/noice.jpg &

xset b off &
picom &
lxpolkit &
# Layout
setxkbmap -layout us,il -option 'grp:alt_shift_toggle'
# Mouse
xinput --set-prop 12 'libinput Accel Speed' -1

bspc monitor -d I II III IV V VI VII VIII IX X


bspc config focused_border_color "#871e1e"
bspc config normal_border_color  "#620404"

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 	2
bspc config bottom_padding 	0
bspc config left_padding 	0
bspc config right_padding 	0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus true

# Apps
bspc rule --add Brave-browser desktop=^1 follow=on state=tiled
bspc rule --add Alacritty desktop=^2 follow=on state=tiled
bspc rule --add discord desktop=^3 follow=on state=tiled
bspc rule --add steam desktop=^4 follow=on state=tiled
bspc rule --add lunarclient desktop=^4 follow=on state=tiled

# Startup apps 
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x kdeconnect-indicator > /dev/null || kdeconnect-indicator &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x corectrl > /dev/null || corectrl &

# Polybar
bash /home/audioz/.config/polybar/launch.sh &
